name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Firebase Config
        run: |
          echo '${{ secrets.FIREBASE_CONFIG }}' > firebase-config.js
          cat firebase-config.js

      - name: Validate Firebase Config
        run: |
          echo "Validating Firebase config format..."
          if ! grep -q "const firebaseConfig" firebase-config.js; then
            echo "ERROR: Firebase config does not contain 'const firebaseConfig'"
            exit 1
          fi
          if ! grep -q "firebase.initializeApp(firebaseConfig)" firebase-config.js; then
            echo "ERROR: Firebase config does not initialize Firebase"
            exit 1
          fi
          if ! grep -q "const db = firebase.database()" firebase-config.js; then
            echo "ERROR: Firebase config does not set up database reference"
            exit 1
          fi
          echo "Firebase config format looks good!"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: master